import type { Activity, Expense, Group, Settlement, User } from "@/types";

// ─── Mock current user ────────────────────────────────────────────────────────
export const MOCK_ME: User = {
  id: "user-1",
  name: "Alex Chen",
  email: "alex@example.com",
  initials: "AC",
  defaultCurrency: "USD",
};

// ─── Mock other users ─────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  MOCK_ME,
  {
    id: "user-2",
    name: "Jordan Lee",
    email: "jordan@example.com",
    initials: "JL",
    defaultCurrency: "USD",
  },
  {
    id: "user-3",
    name: "Sam Rivera",
    email: "sam@example.com",
    initials: "SR",
    defaultCurrency: "EUR",
  },
  {
    id: "user-4",
    name: "Morgan Kim",
    email: "morgan@example.com",
    initials: "MK",
    defaultCurrency: "USD",
  },
  {
    id: "user-5",
    name: "Taylor Nguyen",
    email: "taylor@example.com",
    initials: "TN",
    defaultCurrency: "GBP",
  },
];

function getUser(id: string): User {
  return MOCK_USERS.find((u) => u.id === id) ?? MOCK_ME;
}

// ─── Mock groups ──────────────────────────────────────────────────────────────
export const MOCK_GROUPS: Group[] = [
  {
    id: "group-1",
    name: "Tokyo Trip 🇯🇵",
    icon: "Plane",
    description: "Spring 2025 Japan adventure",
    currency: "JPY",
    createdAt: new Date("2025-03-01"),
    createdBy: "user-1",
    totalExpenses: 284500,
    members: [
      { userId: "user-1", user: getUser("user-1"), balance: 45200 },
      { userId: "user-2", user: getUser("user-2"), balance: -22600 },
      { userId: "user-3", user: getUser("user-3"), balance: -22600 },
    ],
  },
  {
    id: "group-2",
    name: "Apartment Shared",
    icon: "Home",
    description: "Monthly shared expenses",
    currency: "USD",
    createdAt: new Date("2025-01-15"),
    createdBy: "user-2",
    totalExpenses: 4200,
    members: [
      { userId: "user-1", user: getUser("user-1"), balance: -85.5 },
      { userId: "user-2", user: getUser("user-2"), balance: 170.0 },
      { userId: "user-4", user: getUser("user-4"), balance: -84.5 },
    ],
  },
  {
    id: "group-3",
    name: "Weekend Getaway",
    icon: "Tent",
    description: "Camping trip July 2025",
    currency: "USD",
    createdAt: new Date("2025-07-01"),
    createdBy: "user-1",
    totalExpenses: 680,
    members: [
      { userId: "user-1", user: getUser("user-1"), balance: 127.5 },
      { userId: "user-3", user: getUser("user-3"), balance: -63.75 },
      { userId: "user-4", user: getUser("user-4"), balance: -63.75 },
      { userId: "user-5", user: getUser("user-5"), balance: 0 },
    ],
  },
  {
    id: "group-4",
    name: "Europe Euro Trip",
    icon: "Globe",
    description: "Backpacking Europe",
    currency: "EUR",
    createdAt: new Date("2025-06-01"),
    createdBy: "user-5",
    totalExpenses: 3250,
    members: [
      { userId: "user-1", user: getUser("user-1"), balance: 0 },
      { userId: "user-5", user: getUser("user-5"), balance: 220 },
      { userId: "user-2", user: getUser("user-2"), balance: -220 },
    ],
  },
];

// ─── Mock expenses ────────────────────────────────────────────────────────────
export const MOCK_EXPENSES: Expense[] = [
  {
    id: "exp-1",
    groupId: "group-1",
    title: "Shinjuku dinner",
    amount: 18500,
    currency: "JPY",
    category: "food",
    paidBy: "user-1",
    paidByUser: getUser("user-1"),
    splitMethod: "equal",
    splits: [
      { userId: "user-1", user: getUser("user-1"), amount: 6167, paid: true },
      { userId: "user-2", user: getUser("user-2"), amount: 6167, paid: false },
      { userId: "user-3", user: getUser("user-3"), amount: 6166, paid: false },
    ],
    date: new Date("2025-03-12"),
    createdAt: new Date("2025-03-12"),
    notes: "Amazing ramen and gyoza!",
  },
  {
    id: "exp-2",
    groupId: "group-1",
    title: "Shinkansen tickets",
    amount: 48000,
    currency: "JPY",
    category: "transport",
    paidBy: "user-2",
    paidByUser: getUser("user-2"),
    splitMethod: "equal",
    splits: [
      { userId: "user-1", user: getUser("user-1"), amount: 16000, paid: false },
      { userId: "user-2", user: getUser("user-2"), amount: 16000, paid: true },
      { userId: "user-3", user: getUser("user-3"), amount: 16000, paid: false },
    ],
    date: new Date("2025-03-14"),
    createdAt: new Date("2025-03-14"),
  },
  {
    id: "exp-3",
    groupId: "group-2",
    title: "Internet bill",
    amount: 89.99,
    currency: "USD",
    category: "utilities",
    paidBy: "user-2",
    paidByUser: getUser("user-2"),
    splitMethod: "equal",
    splits: [
      { userId: "user-1", user: getUser("user-1"), amount: 30, paid: false },
      { userId: "user-2", user: getUser("user-2"), amount: 30, paid: true },
      { userId: "user-4", user: getUser("user-4"), amount: 29.99, paid: false },
    ],
    date: new Date("2025-06-01"),
    createdAt: new Date("2025-06-01"),
  },
  {
    id: "exp-4",
    groupId: "group-3",
    title: "Campsite booking",
    amount: 340,
    currency: "USD",
    category: "accommodation",
    paidBy: "user-1",
    paidByUser: getUser("user-1"),
    splitMethod: "equal",
    splits: [
      { userId: "user-1", user: getUser("user-1"), amount: 85, paid: true },
      { userId: "user-3", user: getUser("user-3"), amount: 85, paid: false },
      { userId: "user-4", user: getUser("user-4"), amount: 85, paid: false },
      { userId: "user-5", user: getUser("user-5"), amount: 85, paid: false },
    ],
    date: new Date("2025-07-04"),
    createdAt: new Date("2025-07-04"),
  },
  {
    id: "exp-5",
    groupId: "group-2",
    title: "Electricity bill",
    amount: 145.0,
    currency: "USD",
    category: "utilities",
    paidBy: "user-2",
    paidByUser: getUser("user-2"),
    splitMethod: "equal",
    splits: [
      { userId: "user-1", user: getUser("user-1"), amount: 48.33, paid: false },
      { userId: "user-2", user: getUser("user-2"), amount: 48.34, paid: true },
      { userId: "user-4", user: getUser("user-4"), amount: 48.33, paid: false },
    ],
    date: new Date("2025-06-15"),
    createdAt: new Date("2025-06-15"),
  },
  {
    id: "exp-6",
    groupId: "group-4",
    title: "Barcelona Airbnb",
    amount: 680,
    currency: "EUR",
    category: "accommodation",
    paidBy: "user-5",
    paidByUser: getUser("user-5"),
    splitMethod: "equal",
    splits: [
      { userId: "user-1", user: getUser("user-1"), amount: 226.67, paid: false },
      { userId: "user-5", user: getUser("user-5"), amount: 226.67, paid: true },
      { userId: "user-2", user: getUser("user-2"), amount: 226.66, paid: false },
    ],
    date: new Date("2025-06-10"),
    createdAt: new Date("2025-06-10"),
  },
];

// ─── Mock settlements ─────────────────────────────────────────────────────────
export const MOCK_SETTLEMENTS: Settlement[] = [
  {
    id: "settle-1",
    groupId: "group-1",
    fromUserId: "user-2",
    toUserId: "user-1",
    fromUser: getUser("user-2"),
    toUser: getUser("user-1"),
    amount: 16000,
    currency: "JPY",
    date: new Date("2025-03-20"),
    note: "Shinkansen payback",
  },
];

// ─── Mock activity ────────────────────────────────────────────────────────────
export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    type: "expense",
    groupId: "group-1",
    group: MOCK_GROUPS[0],
    expense: MOCK_EXPENSES[1],
    userId: "user-2",
    user: getUser("user-2"),
    description: "Jordan added Shinkansen tickets",
    amount: 48000,
    currency: "JPY",
    date: new Date("2025-03-14"),
  },
  {
    id: "act-2",
    type: "expense",
    groupId: "group-4",
    group: MOCK_GROUPS[3],
    expense: MOCK_EXPENSES[5],
    userId: "user-5",
    user: getUser("user-5"),
    description: "Taylor added Barcelona Airbnb",
    amount: 680,
    currency: "EUR",
    date: new Date("2025-06-10"),
  },
  {
    id: "act-3",
    type: "expense",
    groupId: "group-2",
    group: MOCK_GROUPS[1],
    expense: MOCK_EXPENSES[4],
    userId: "user-2",
    user: getUser("user-2"),
    description: "Jordan added Electricity bill",
    amount: 145,
    currency: "USD",
    date: new Date("2025-06-15"),
  },
  {
    id: "act-4",
    type: "expense",
    groupId: "group-3",
    group: MOCK_GROUPS[2],
    expense: MOCK_EXPENSES[3],
    userId: "user-1",
    user: getUser("user-1"),
    description: "You added Campsite booking",
    amount: 340,
    currency: "USD",
    date: new Date("2025-07-04"),
  },
  {
    id: "act-5",
    type: "settlement",
    groupId: "group-1",
    group: MOCK_GROUPS[0],
    settlement: MOCK_SETTLEMENTS[0],
    userId: "user-2",
    user: getUser("user-2"),
    description: "Jordan paid you back",
    amount: 16000,
    currency: "JPY",
    date: new Date("2025-03-20"),
  },
  {
    id: "act-6",
    type: "expense",
    groupId: "group-2",
    group: MOCK_GROUPS[1],
    expense: MOCK_EXPENSES[2],
    userId: "user-2",
    user: getUser("user-2"),
    description: "Jordan added Internet bill",
    amount: 89.99,
    currency: "USD",
    date: new Date("2025-06-01"),
  },
];
