(() => {
  const root = document.querySelector('#app');
  const platform = document.body.dataset.platform || 'ios';
  const state = { route: 'splash', history: [], filter: 'All', expenseStep: 1, onboarding: 0, sent: false, dark: false };
  const icons = {
    back: '<path d="m15 18-6-6 6-6"/>', bell: '<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',
    user: '<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>', plus: '<path d="M12 5v14M5 12h14"/>',
    home: '<path d="m3 11 9-8 9 8v10h-6v-6H9v6H3z"/>', groups: '<circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20a6 6 0 0 1 12 0M14 15a5 5 0 0 1 7 5"/>',
    friends: '<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>', activity: '<path d="M3 12h4l2-6 4 12 2-6h6"/>',
    search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>', arrow: '<path d="m9 18 6-6-6-6"/>', wallet: '<path d="M4 6h15a2 2 0 0 1 2 2v10H4a2 2 0 0 1-2-2V6a3 3 0 0 1 3-3h12"/><path d="M16 11h5"/>',
    plane: '<path d="M22 2 9 15M22 2l-7 20-4-9-9-4z"/>', food: '<path d="M7 3v8M4 3v5a3 3 0 0 0 6 0V3M7 11v10M17 3c-3 3-3 8 0 9v9M17 3v9"/>',
    check: '<path d="m5 12 4 4L19 6"/>', swap: '<path d="m7 7-4 4 4 4M17 17l4-4-4-4M3 11h18"/>', chart: '<path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/>',
    settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H3v-4h.1a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',
    mail: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>', lock: '<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
    eye: '<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12"/><circle cx="12" cy="12" r="3"/>', calendar: '<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',
    receipt: '<path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6"/>', comment: '<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/>',
    moon: '<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>', logout: '<path d="M10 17l5-5-5-5M15 12H3M15 3h6v18h-6"/>',
  };
  const icon = (name) => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.arrow}</svg>`;
  const button = (label, action, kind = 'primary') => `<button class="btn btn-${kind}" data-action="${action}">${label}</button>`;
  const iconButton = (name, action, label) => `<button class="icon-btn" data-action="${action}" aria-label="${label}">${icon(name)}</button>`;
  const topbar = (title, right = '', back = true) => `<header class="topbar" data-od-id="${slug(title)}-header"><div class="actions">${back ? iconButton('back', 'back', 'Go back') : ''}<h1>${title}</h1></div>${right}</header>`;
  const slug = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const avatar = (name, group = false) => `<span class="avatar ${group ? 'group' : ''}">${name.split(/\s/).map(x => x[0]).slice(0, 2).join('')}</span>`;
  const row = (title, copy, end = '', action = '') => `<div class="row" ${action ? `data-action="${action}"` : ''}><div class="row-main"><div class="row-title"><span>${title}</span>${end ? `<span>${end}</span>` : ''}</div><div class="row-copy">${copy}</div></div>${action ? icon('arrow') : ''}</div>`;
  const personRow = (name, copy, end, action = 'friend-detail') => `<div class="row" data-action="${action}">${avatar(name)}<div class="row-main"><div class="row-title"><span>${name}</span><span>${end}</span></div><div class="row-copy">${copy}</div></div>${icon('arrow')}</div>`;
  const groupRow = (name, copy, end, action = 'group-detail') => `<div class="row" data-action="${action}">${avatar(name, true)}<div class="row-main"><div class="row-title"><span>${name}</span><span>${end}</span></div><div class="row-copy">${copy}</div></div>${icon('arrow')}</div>`;
  const search = (placeholder) => `<label class="search">${icon('search')}<input class="field" type="search" placeholder="${placeholder}" data-search></label>`;
  const section = (title, content, action = '') => `<section class="section" data-od-id="${slug(title)}"><div class="section-head"><h2>${title}</h2>${action ? `<button class="section-link" data-action="${action}">View all</button>` : ''}</div><div class="list glass">${content}</div></section>`;
  const input = (label, placeholder, type = 'text', required = false) => `<label class="field-label">${label}</label><input class="field" type="${type}" placeholder="${placeholder}" ${required ? 'required' : ''}>`;
  const filterChips = (labels) => `<div class="chips">${labels.map(label => `<button class="chip ${state.filter === label ? 'active' : ''}" data-filter="${label}">${label}</button>`).join('')}</div>`;
  const tabs = (active) => `<nav class="tabs glass" data-od-id="main-navigation">${[['dashboard','home','Home'],['groups','groups','Groups'],['friends','friends','Friends'],['activity','activity','Activity']].map(([route, glyph, label]) => `<button class="tab ${active === route ? 'active' : ''}" data-route="${route}">${icon(glyph)}<span>${label}</span></button>`).join('')}</nav>`;
  const shell = (content, tab = '', fab = false) => `${content}${tab ? tabs(tab) : ''}${fab ? `<button class="fab visible" data-route="expense-new" aria-label="Add expense">${icon('plus')}</button>` : ''}`;

  const screens = {
    splash: () => `<main class="splash" data-od-id="session-loading-screen"><div><div class="splash-mark">S</div><p>SPLT.</p></div></main>`,
    welcome: () => `<main class="screen auth-screen" data-od-id="welcome-screen"><div class="auth-mark">S</div><div class="illustration glass"><div class="orb">${icon('wallet')}</div></div><p class="greeting">SPLIT MADE SIMPLE</p><h1 class="title-xl">Money between friends, made clear.</h1><p class="subtitle">Record shared costs, see balances at a glance, and settle without awkward follow-ups.</p>${button('Get Started','register')}${platform === 'ios' ? `<div class="social">${button('Continue with Apple','login','secondary')}</div>` : ''}<div class="social">${button('Continue with Google','login','secondary')}</div><button class="text-btn" data-action="login">Already have an account? Log in</button></main>`,
    login: () => `<main class="screen auth-screen" data-od-id="login-screen">${topbar('Splt', '', true)}<div class="auth-mark">S</div><h1 class="title-xl">Welcome<br>back.</h1><p class="subtitle">Sign in and pick up where you left off.</p><form data-form="login" class="form-grid">${input('Email Address','hello@splt.app','email',true)}${input('Password','••••••••','password',true)}<button class="text-btn" type="button" data-action="forgot">Forgot Password?</button>${button('Sign In','submit-login')}</form><div class="divider">or</div>${button('Continue with Google','submit-login','secondary')}<button class="text-btn" data-action="register">New to Splt? Create one</button></main>`,
    register: () => `<main class="screen auth-screen" data-od-id="register-screen">${topbar('Create account')}<h1 class="title-xl">Create<br>account.</h1><p class="subtitle">Enter your details to get started.</p><form data-form="register">${input('Full Name','John Doe','text',true)}${input('Email Address','hello@splt.app','email',true)}${input('Password','At least 6 characters','password',true)}<div class="strength"><i class="on"></i><i class="on"></i><i></i><i></i></div>${input('Confirm Password','Repeat password','password',true)}<div class="inline form-card glass" style="margin-top:14px"><span>I accept the Terms of Service and Privacy Policy.</span><button type="button" class="toggle on" data-toggle aria-label="Accept terms"></button></div>${button('Create Account','submit-register')}</form></main>`,
    forgot: () => `<main class="screen auth-screen" data-od-id="forgot-password-screen">${topbar('Reset password')}<div class="auth-mark">${icon(state.sent ? 'mail' : 'lock')}</div><h1 class="title-xl">${state.sent ? 'Check your<br>inbox.' : 'Reset<br>password.'}</h1><p class="subtitle">${state.sent ? 'We’ve sent a reset link to hello@splt.app. Check spam if it does not arrive.' : 'We’ll send a reset link to your email address.'}</p>${state.sent ? `${button('Resend email','send-reset','secondary')}<button class="text-btn" data-action="login">Back to Sign In</button>` : `<form data-form="forgot">${input('Email Address','hello@splt.app','email',true)}${button('Send Reset Link','send-reset')}</form>`}</main>`,
    onboarding: () => { const slides = [{t:'Track\nBalances',s:'Know where you stand',c:'See who owes what at a glance. No more awkward conversations about money.',i:'wallet'},{t:'Shared\nGroups',s:'Split with anyone',c:'Create groups for trips, roommates, or nights out. Every expense stays organized.',i:'groups'},{t:'Settle\nUp Fast',s:'Pay and be paid',c:'Record payments in seconds. Everyone stays in the loop.',i:'swap'},{t:'Your\nCurrency',s:'Multi-currency ready',c:'Pick a default currency. We’ll handle the conversions when you travel.',i:'chart'}]; const x=slides[state.onboarding]; return `<main class="screen auth-screen" data-od-id="onboarding-screen"><div class="topbar"><button class="text-btn" data-action="skip">Skip</button><span>${state.onboarding+1} / 4</span></div><div class="progress">${slides.map((_,i)=>`<span class="${i<=state.onboarding?'on':''}"></span>`).join('')}</div><div class="illustration glass"><div class="orb">${icon(x.i)}</div></div><p class="greeting">${x.s.toUpperCase()}</p><h1 class="title-xl">${x.t.replace('\n','<br>')}</h1><p class="subtitle">${x.c}</p>${state.onboarding===3?`<label class="field-label">DEFAULT CURRENCY</label><select class="field"><option>USD · US Dollar</option><option>EUR · Euro</option><option>GBP · British Pound</option></select>`:''}<div style="margin-top:auto" class="button-row">${state.onboarding ? button('Back','onboarding-back','secondary') : '<span></span>'}${button(state.onboarding===3?'Get Started':'Next','onboarding-next')}</div></main>`; },
    dashboard: () => shell(`<main class="screen" data-od-id="dashboard-screen"><header class="topbar"><div><p class="greeting">GOOD MORNING</p><h1>Alex</h1></div><div class="actions">${iconButton('bell','notifications','Notifications')}${iconButton('user','profile','Profile')}</div></header><section class="hero-balance glass" data-od-id="money-state"><span class="label">Today’s money state</span><strong class="amount">$184.20 owed to you</strong><div class="metrics"><div class="metric"><span class="label">You owe</span><strong class="negative">$42.50</strong></div><div class="metric"><span class="label">Owed to you</span><strong class="positive">$226.70</strong></div></div></section><div class="button-row">${button('+ Add Expense','expense-new')}${button('Settle up','settle','secondary')}</div>${section('This month',row('18 expenses','Average $68.89','$1,240','stats'))}${section('Need attention',personRow('Maya Chen','Lisbon trip · 4 days ago','$92.40'))}${section('Groups',groupRow('Lisbon','4 members · 8 expenses','+$126.30')+groupRow('Apartment','3 members · updated today','−$42.50'),'groups')}${section('Recent activity',row('Dinner at Prado','You paid · Lisbon','+$44.80','expense-detail')+row('Wi-Fi bill','Sam paid · Apartment','−$18.00','expense-detail'))}</main>`,'dashboard',false),
    groups: () => shell(`<main class="screen" data-od-id="groups-screen">${topbar('Groups',iconButton('plus','group-new','Create group'),false)}<div class="metrics form-card glass"><div class="metric"><span class="label">You owe</span><strong class="negative">$42.50</strong></div><div class="metric"><span class="label">Owed</span><strong class="positive">$226.70</strong></div></div>${search('Search your groups...')}${filterChips(['All','You owe','Owes you','Settled'])}<section class="section"><div class="list glass">${groupRow('Lisbon','4 members · 8 expenses','+$126.30')+groupRow('Apartment','3 members · 14 expenses','−$42.50')+groupRow('Sunday Rides','5 members · all clear','Settled')}</div></section></main>`,'groups',platform==='android'),
    'group-new': () => `<main class="screen" data-od-id="new-group-screen">${topbar('Create new group')}<form data-form="new-group"><div class="form-card glass">${input('Title','e.g. Day trip to Warsaw','text',true)}<label class="field-label">Group icon</label><div class="chips"><button type="button" class="chip active">Plane</button><button type="button" class="chip">Home</button><button type="button" class="chip">Food</button></div></div><div class="form-card glass"><div class="inline"><h2>Participants</h2><button type="button" class="text-btn" data-action="add-person">+ Add</button></div>${personRow('Alex Morgan','You','')}${personRow('Maya Chen','Friend','')}</div><div class="form-card glass"><label class="field-label">Currency</label><select class="field"><option>USD · US Dollar</option><option>EUR · Euro</option></select></div>${button('Create group','create-group')}<p class="greeting" style="text-align:center;margin-top:12px">ALL PARTICIPANTS WILL RECEIVE AN INVITE</p></form></main>`,
    'group-detail': () => `<main class="screen" data-od-id="group-detail-screen">${topbar('Lisbon',iconButton('settings','group-settings','Group settings'))}<section class="hero-balance glass"><span class="label">You are owed</span><strong class="amount positive">$126.30</strong><div class="inline"><span>4 members</span><div class="actions">${avatar('AM')}${avatar('MC')}${avatar('SL')}</div></div></section>${section('Group balances',personRow('Maya Chen','owes you','$92.40')+personRow('Sam Lee','owes you','$33.90'))}${section('Transactions',row('Dinner at Prado','You paid · Jun 18','$164.00','expense-detail')+row('Airport transfer','Maya paid · Jun 17','$58.00','expense-detail'))}<div class="button-row">${button('Settle Up','settle','secondary')}${button('Add Expense','expense-new')}</div></main>`,
    'group-settings': () => `<main class="screen" data-od-id="group-settings-screen">${topbar('Group settings')}<form data-form="settings">${section('Identity',`<div class="form-card">${input('Group Name','Lisbon')}${input('Description (Optional)','Summer city break')}</div>`)}${section('Finance',`<div class="form-card"><label class="field-label">Base Currency</label><select class="field"><option>USD · US Dollar</option><option>EUR · Euro</option></select><label class="field-label">Default Split Method</label><select class="field"><option>Equal</option><option>Custom</option><option>Percentage</option></select><div class="inline" style="margin-top:14px"><span><strong>Simplify Debts</strong><br><small>Reduce payments between members</small></span><button type="button" class="toggle on" data-toggle></button></div></div>`)}${section('Members',personRow('Alex Morgan','You','')+personRow('Maya Chen','Owes $92.40','Remove'))}<div class="button-row">${button('Delete Group','confirm-delete','danger')}${button('Save Changes','save-settings')}</div></form></main>`,
    friends: () => shell(`<main class="screen" data-od-id="friends-screen">${topbar('Friends',iconButton('plus','friend-new','Add friend'),false)}<section class="hero-balance glass"><div class="metrics"><div><span class="label">Owed to you</span><strong class="amount-sm positive">$226.70</strong></div><div><span class="label">You owe</span><strong class="amount-sm negative">$42.50</strong></div></div></section>${search('Search friends or email')}${filterChips(['All','Owes you','You owe','Settled'])}${section('Needs attention',personRow('Maya Chen','Lisbon · owes you','$92.40')+personRow('Noah Williams','Dinner · you owe','$42.50'))}${section('Settled',personRow('Sam Lee','Last split 2 weeks ago','Clear'))}</main>`,'friends',false),
    'friend-new': () => `<main class="screen" data-od-id="new-friend-screen">${topbar('Add Friend')}${search('Search by name or email...')}<div class="empty glass"><div class="avatar" style="margin:auto">+</div><h3>Find friends</h3><p>Search by name or email address to send a friend request.</p></div><section class="section"><div class="list glass">${personRow('Maya Chen','maya@example.com','Add','send-request')+personRow('Noah Williams','noah@example.com','Requested','')}</div></section></main>`,
    'friend-detail': () => `<main class="screen" data-od-id="friend-detail-screen">${topbar('Maya Chen',iconButton('settings','friend-options','Friend options'))}<div style="text-align:center;margin-bottom:18px">${avatar('Maya Chen')}<p class="subtitle" style="margin:8px auto">maya@example.com</p></div><section class="hero-balance glass"><span class="label">Maya owes you</span><strong class="amount positive">$92.40</strong></section>${section('Shared Groups',groupRow('Lisbon','Latest: Dinner at Prado','+$92.40'))}${section('Recent Activity',row('Dinner at Prado','You paid · Jun 18','+$44.80','expense-detail'))}<div class="button-row">${button('Remind','remind','secondary')}${button('Add Expense','expense-new')}</div></main>`,
    'expense-new': () => `<main class="screen" data-od-id="new-expense-screen">${topbar(state.expenseStep===1?'New expense':'Expense details')}<div class="progress"><span class="on"></span><span class="${state.expenseStep===2?'on':''}"></span></div>${state.expenseStep===1?`<h2>Who is this expense with?</h2><p class="subtitle">Choose one group or any number of friends before entering the amount.</p><div class="segmented glass"><button class="active">Friends</button><button>Groups</button></div>${search('Search friends or groups')}${section('People',personRow('Maya Chen','Lisbon','Selected','')+personRow('Sam Lee','Apartment','Add',''))}<button class="btn btn-primary btn-block" data-action="expense-next">Continue</button>`:`<section class="form-card glass"><span class="label">Amount</span><input class="field money-input" inputmode="decimal" value="84.00"><input class="field" placeholder="What was it for?" value="Dinner at Prado"></section><div class="segmented glass"><button class="active">Equal</button><button>Custom</button><button>Percent</button></div><section class="form-card glass"><div class="inline"><span>Paid by</span><strong>You</strong></div><div class="inline" style="margin-top:14px"><span>Split preview</span><strong>$42.00 each</strong></div></section>${input('Category','Food & Drink')}${input('Date','Jun 18, 2026','date')}<button class="btn btn-primary btn-block" data-action="save-expense">Add expense</button>`}</main>`,
    'expense-detail': () => `<main class="screen" data-od-id="expense-detail-screen">${topbar('Expense',iconButton('settings','edit-expense','Edit expense'))}<div style="text-align:center;padding:18px 0"><div class="avatar group" style="margin:auto">${icon('food')}</div><h1 class="title" style="margin-top:12px">Dinner at Prado</h1><strong class="amount">$164.00</strong></div><section class="form-card glass"><div class="inline"><span>Date</span><strong>Jun 18, 2026</strong></div><div class="inline" style="margin-top:14px"><span>Paid by</span><strong>You</strong></div><div class="inline" style="margin-top:14px"><span>Group</span><strong>Lisbon</strong></div></section>${section('Split Breakdown',personRow('Alex Morgan','Paid the bill','$82.00','')+personRow('Maya Chen','Owes','$82.00',''))}${section('Comments',row('No comments yet','Start the conversation','',''))}<div class="search">${icon('comment')}<input class="field" placeholder="Add a comment..."></div><button class="btn btn-danger btn-block" data-action="confirm-delete">Delete Expense</button></main>`,
    settle: () => `<main class="screen" data-od-id="settle-up-screen">${topbar('Settle Up')}<div class="form-card glass"><div class="inline"><div style="text-align:center">${avatar('Alex Morgan')}<strong style="display:block;margin-top:6px">You</strong></div>${icon('swap')}<div style="text-align:center">${avatar('Maya Chen')}<strong style="display:block;margin-top:6px">Maya</strong></div></div></div><label class="field-label">Amount (USD)</label><input class="field money-input" inputmode="decimal" value="92.40"><div class="chips"><button class="chip active">Full: $92.40</button><button class="chip">Half: $46.20</button></div><div class="form-card glass"><label class="field-label">Add a note</label><textarea class="field" placeholder="Payment details..."></textarea><label class="field-label">Link to Group</label><select class="field"><option>Lisbon</option><option>None</option></select></div><div class="form-card glass"><span class="label">Recording payment</span><p><strong>You receive $92.40 from Maya</strong></p></div><button class="btn btn-primary btn-block" data-action="record-settlement">Record $92.40</button></main>`,
    activity: () => shell(`<main class="screen" data-od-id="activity-screen">${topbar('Activity','',false)}${search('Search activity...')}${filterChips(['All','Expenses','Settlements','Groups','Friends'])}${section('Today',row('Dinner at Prado','You lent Maya','$82.00','expense-detail')+row('Settlement recorded','Noah paid you','$24.00','friend-detail'))}${section('Yesterday',row('Lisbon created','You created a group','','group-detail')+row('Airport transfer','Maya paid · You owe','$29.00','expense-detail'))}</main>`,'activity',false),
    notifications: () => `<main class="screen" data-od-id="notifications-screen">${topbar('Notifications')}${section('New',personRow('Taylor Reed','Wants to connect','Accept','accept-friend')+personRow('Jordan Kim','Wants to connect','Accept','accept-friend'))}</main>`,
    stats: () => `<main class="screen" data-od-id="analytics-screen">${topbar('Analytics')}<div class="segmented glass"><button>Week</button><button class="active">Month</button><button>3 Months</button><button>Year</button></div><section class="hero-balance glass"><span class="label">Spending summary</span><strong class="amount">$1,240.00</strong><div class="metrics"><div class="metric"><span class="label">Expenses</span><strong>18</strong></div><div class="metric"><span class="label">Average</span><strong>$68.89</strong></div></div></section><section class="form-card glass"><div class="section-head"><h2>Trend</h2><span class="label">JUNE</span></div><div class="bars">${[32,48,28,76,54,94,62].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></section><section class="form-card glass"><h2>Categories</h2><div class="donut"></div></section>${section('Top Expenses',row('Apartment rent','Housing','$620.00','expense-detail')+row('Dinner at Prado','Food & Drink','$164.00','expense-detail'))}</main>`,
    profile: () => `<main class="screen" data-od-id="profile-screen">${topbar('Profile',iconButton('settings','profile-edit','Edit profile'))}<div style="text-align:center;margin:8px 0 20px">${avatar('Alex Morgan')}<h2 style="margin:10px 0 3px">Alex Morgan</h2><p class="subtitle" style="margin:auto">alex@example.com</p></div><section class="hero-balance glass"><div class="metrics"><div class="metric"><span class="label">Groups</span><strong>3</strong></div><div class="metric"><span class="label">Net balance</span><strong class="positive">+$184.20</strong></div></div></section>${section('Preferences',row('Dark Mode','Switch between themes','', 'toggle-theme')+row('Default Currency','USD · US Dollar','USD','currency'))}${section('Account',row('Change Password','Update account security','','change-password')+row('Tell a Friend','Share Splt','','share')+row('Log Out','Sign out of this device','','logout'))}<button class="btn btn-danger btn-block" data-action="delete-account">Delete Account</button><p class="greeting" style="text-align:center;margin:18px">SPLT V1.0.0</p></main>`,
    'profile-edit': () => `<main class="screen" data-od-id="edit-profile-screen">${topbar('Edit Profile')}<form data-form="profile-edit"><div style="text-align:center;margin:20px">${avatar('Alex Morgan')}</div><div class="form-card glass">${input('Name','Alex Morgan')}<label class="field-label">Email</label><input class="field" value="alex@example.com" disabled><p class="row-copy">Email cannot be changed</p></div><button class="btn btn-primary btn-block" data-action="save-profile">Save Changes</button></form></main>`,
    'change-password': () => `<main class="screen" data-od-id="change-password-screen">${topbar('Change Password')}<form data-form="password"><div class="form-card glass">${input('New password','At least 6 characters','password',true)}<div class="strength"><i class="on"></i><i class="on"></i><i class="on"></i><i></i></div><p class="row-copy">Good</p>${input('Confirm new password','Repeat password','password',true)}</div><button class="btn btn-primary btn-block" data-action="update-password">Update Password</button></form></main>`,
  };

  const actionRoutes = { login:'login', register:'register', forgot:'forgot', profile:'profile', notifications:'notifications', 'group-new':'group-new', 'group-detail':'group-detail', 'group-settings':'group-settings', 'friend-new':'friend-new', 'friend-detail':'friend-detail', 'expense-new':'expense-new', 'expense-detail':'expense-detail', settle:'settle', 'profile-edit':'profile-edit', 'change-password':'change-password', stats:'stats' };
  function navigate(route, replace = false) { if (!screens[route]) return; if (!replace) state.history.push(state.route); state.route = route; render(); }
  function goBack() { const previous = state.history.pop(); navigate(previous || 'dashboard', true); }
  function showSheet(title, copy, confirm = 'Done') { root.insertAdjacentHTML('beforeend', `<div class="sheet-backdrop" data-dismiss><section class="sheet glass" role="dialog" aria-modal="true"><div class="sheet-handle"></div><h2>${title}</h2><p>${copy}</p><div class="button-row">${button('Cancel','dismiss','secondary')}${button(confirm,'confirm-sheet',confirm==='Delete'?'danger':'primary')}</div></section></div>`); }
  function toast(message) { const old = root.querySelector('.toast'); if (old) old.remove(); root.insertAdjacentHTML('beforeend', `<div class="toast glass">${icon('check')}<strong>${message}</strong></div>`); setTimeout(()=>root.querySelector('.toast')?.remove(),2200); }
  function render() { root.innerHTML = screens[state.route](); root.querySelector('.screen')?.scrollTo(0,0); bind(); if (state.route === 'splash') setTimeout(() => navigate('welcome', true), 900); }
  function bind() {
    root.querySelectorAll('[data-route]').forEach(el => el.addEventListener('click', () => navigate(el.dataset.route)));
    root.querySelectorAll('[data-filter]').forEach(el => el.addEventListener('click', () => { state.filter = el.dataset.filter; render(); }));
    root.querySelectorAll('[data-toggle]').forEach(el => el.addEventListener('click', () => el.classList.toggle('on')));
    root.querySelectorAll('[data-action]').forEach(el => el.addEventListener('click', event => {
      const action = el.dataset.action; if (actionRoutes[action]) return navigate(action);
      if (action === 'back') return goBack();
      if (action === 'submit-login') return navigate('dashboard');
      if (action === 'submit-register') return navigate('onboarding');
      if (action === 'send-reset') { state.sent = true; render(); return; }
      if (action === 'skip') return navigate('dashboard');
      if (action === 'onboarding-next') { if (state.onboarding < 3) { state.onboarding++; render(); } else navigate('dashboard'); return; }
      if (action === 'onboarding-back') { state.onboarding=Math.max(0,state.onboarding-1); render(); return; }
      if (action === 'expense-next') { state.expenseStep=2; render(); return; }
      if (action === 'save-expense') { toast('Expense added to Lisbon'); setTimeout(()=>navigate('group-detail'),700); return; }
      if (action === 'record-settlement') { toast('Settlement recorded'); setTimeout(()=>navigate('friend-detail'),700); return; }
      if (action === 'create-group') { toast('Group created'); setTimeout(()=>navigate('group-detail'),700); return; }
      if (action === 'confirm-delete') return showSheet('Delete item?', 'This permanently removes the item and cannot be undone.', 'Delete');
      if (action === 'delete-account') return showSheet('Delete Account?', 'This permanently deletes your account and all associated data. This cannot be undone.', 'Delete');
      if (action === 'friend-options') return showSheet('Maya Chen', 'Send a reminder, settle up, share the balance, or remove this friend.', 'Send reminder');
      if (action === 'add-person') return showSheet('Add to Group', 'Search by name or email to invite another participant.', 'Add');
      if (action === 'currency') return showSheet('Select currency', 'Choose the default money format for expenses and groups.', 'Use USD');
      if (action === 'dismiss') return el.closest('.sheet-backdrop')?.remove();
      if (action === 'confirm-sheet') { el.closest('.sheet-backdrop')?.remove(); toast('Changes saved'); return; }
      if (['save-settings','save-profile','update-password','send-request','accept-friend','remind','share','toggle-theme','logout','edit-expense'].includes(action)) return toast(action === 'remind' ? 'Reminder sent to Maya' : action === 'logout' ? 'Signed out' : 'Changes saved');
      event.preventDefault();
    }));
    root.querySelectorAll('form').forEach(form => form.addEventListener('submit', e => e.preventDefault()));
  }
  render();
})();
